version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install -g @aws-amplify/cli
      
  pre_build:
    commands:
      - echo "Pre-build phase..."
      - ls -la
      
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building application for ${ENVIRONMENT} environment"
      - cp -r application/* .
      - ls -la
      
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Creating appspec.yml for CodeDeploy"
      - cat appspec.yml

artifacts:
  files:
    - '**/*'
  base-directory: .